version: '3.8'

services:
  web:
    build: .
    command: gunicorn -c gunicorn_config.py config.wsgi:application
    entrypoint: /app/docker-entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: